### ISSUE TITLE
Is the project open for commercial collaboration?

### ISSUE THREAD

**Issue by akhekade** [meherett/swap#7]
Hi,
   We are looking funding multiple developers who can enable cross chain swap of assets from Ethereum and ERC-20 assets to XinFin[XDC] Network. (eth compatible chain)

  The interface would look something like this :
https://bancor.xdc.network/

USDT <- -> USDTx
USDC <--> USDCx
ETH <--> ETHx

and so on. 

Here are specs for XinFin[XDC] Network

XinFin Network: https://xdc.network/home
Github:- https://github.com/XinFinOrg/XDPoSChain
CMC :- https://coinmarketcap.com/currencies/xinfin-network/
Circulating Supply:- https://explorerapi.xinfin.network/publicAPI?module=balance&action=getcirculatingsupply
Total Supply:- https://explorerapi.xinfin.network/publicAPI?module=balance&action=totalXDC
Docker FullNode:- https://github.com/xinfinorg/XinFin-Node
Integration Code example: https://xinfin.org/exchange-listing-resource

Technical Community Support available at:

Telegram Community: https://t.me/XinFinDevelopers
Slack Community: https://xinfin-public.slack.com/messages/CELR2M831/
Slack Invitation Link: https://launchpass.com/xinfin-public
Technical help Resource: http://howto.xinfin.org/

**Comment by meherett** [comment]
@akhekade Yes, it is open. Just send me DM on Telegram https://t.me/meherett.

**Comment by akhekade** [comment]
My colleagues Omkar and Anil will initiate a group on TG
